# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SqoopSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sqoop_tool', models.CharField(max_length=30, verbose_name='sqoop-tool')),
                ('driver', models.CharField(max_length=100)),
                ('connect', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=30)),
                ('hive_database', models.CharField(max_length=30, verbose_name='hive-database')),
                ('fields_terminated_by', models.CharField(max_length=10, verbose_name='fields-terminated-by')),
                ('hive_overwrite', models.BooleanField(verbose_name='hive-overwrite')),
                ('num_mappers', models.IntegerField(verbose_name='num-mappers')),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='sqoopsentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_migrate.SqoopSentence'),
        ),
    ]
