# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_migrate', '0002_auto_20171101_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished_table',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='finished-table'),
        ),
    ]
