# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_migrate', '0004_auto_20171102_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='migrating_table',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='migrating-table'),
        ),
    ]
