# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_migrate', '0006_job_finished_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
